import javax.swing.ImageIcon;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.UIManager;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.awt.Button;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lenovo
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setBackground(new Color(128, 255, 128));
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn02 = new java.awt.Button();
        btn03 = new java.awt.Button();
        btn04 = new java.awt.Button();
        btn01 = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel3.setIcon(new ImageIcon("C:\\Users\\MOHD AFTAB\\eclipse-workspace\\SmartCity-main.zip_expanded\\SmartCity-main\\images\\del_wonder_400x300.jpg")); // NOI18N

        panel2.setBackground(new Color(0, 255, 255));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        label1.setText("SmartCity");

        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setText("Delhi");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rangamati.jpg"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hqdefault.jpg"))); // NOI18N
        
        JLabel lblNewLabel = new JLabel("New label");
        lblNewLabel.setIcon(new ImageIcon("C:\\Users\\MOHD AFTAB\\Desktop\\Java\\lib\\LPU_logo_2_180x100.jpg"));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2Layout.setHorizontalGroup(
        	panel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panel2Layout.createSequentialGroup()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 402, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
        			.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 572, GroupLayout.PREFERRED_SIZE)
        			.addGap(332))
        		.addGroup(panel2Layout.createSequentialGroup()
        			.addGroup(panel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(panel2Layout.createSequentialGroup()
        					.addGap(814)
        					.addComponent(label2, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE))
        				.addGroup(panel2Layout.createSequentialGroup()
        					.addGap(337)
        					.addComponent(label1, GroupLayout.PREFERRED_SIZE, 480, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
        			.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 176, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        panel2Layout.setVerticalGroup(
        	panel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(panel2Layout.createSequentialGroup()
        			.addGroup(panel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(lblNewLabel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
        				.addGroup(panel2Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(label1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
        					.addComponent(label2, GroupLayout.PREFERRED_SIZE, 17, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(panel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 228, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 224, GroupLayout.PREFERRED_SIZE))
        			.addGap(63))
        );
        panel2.setLayout(panel2Layout);

        jLabel2.setIcon(new ImageIcon("C:\\Users\\MOHD AFTAB\\eclipse-workspace\\SmartCity-main.zip_expanded\\SmartCity-main\\images\\india.jpg")); // NOI18N

        jLabel4.setIcon(new ImageIcon("C:\\Users\\MOHD AFTAB\\eclipse-workspace\\SmartCity-main.zip_expanded\\SmartCity-main\\images\\humayu.jpeg")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/9f1cfb7e5712e112324e8903846977e0.jpeg"))); // NOI18N

        jLabel7.setIcon(new ImageIcon("C:\\Users\\MOHD AFTAB\\eclipse-workspace\\SmartCity-main.zip_expanded\\SmartCity-main\\images\\redfort.jpg")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/National_Assembly_of_Bangladesh_(06).jpg"))); // NOI18N

        jLabel9.setIcon(new ImageIcon("C:\\Users\\MOHD AFTAB\\eclipse-workspace\\SmartCity-main.zip_expanded\\SmartCity-main\\images\\intro.png")); // NOI18N

        btn02.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn02.setFont(new Font("Tw Cen MT Condensed Extra Bold", Font.BOLD | Font.ITALIC, 24)); // NOI18N
        btn02.setLabel("Student");
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });

        btn03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn03.setFont(new Font("Jokerman", Font.BOLD | Font.ITALIC, 24)); // NOI18N
        btn03.setLabel("Businessman");
        btn03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn03ActionPerformed(evt);
            }
        });

        btn04.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn04.setFont(new Font("Engravers MT", Font.BOLD | Font.ITALIC, 24)); // NOI18N
        btn04.setLabel("Tourist");
        btn04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn04ActionPerformed(evt);
            }
        });

        btn01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn01.setFont(new Font("Arial Narrow", Font.BOLD | Font.ITALIC, 25)); // NOI18N
        btn01.setLabel("Admin");
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });
        
        lblNewLabel_1 = new JLabel("Who You Are");
        lblNewLabel_1.setHorizontalAlignment(SwingConstants.CENTER);
        lblNewLabel_1.setBackground(new Color(255, 255, 255));
        lblNewLabel_1.setFont(new Font("Lucida Handwriting", Font.BOLD | Font.ITALIC, 26));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1Layout.setHorizontalGroup(
        	panel1Layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(panel2, GroupLayout.DEFAULT_SIZE, 1572, Short.MAX_VALUE)
        		.addGroup(panel1Layout.createSequentialGroup()
        			.addGap(10)
        			.addGroup(panel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(panel1Layout.createSequentialGroup()
        					.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 474, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED))
        				.addGroup(panel1Layout.createParallelGroup(Alignment.LEADING)
        					.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        					.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        			.addGroup(panel1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(panel1Layout.createSequentialGroup()
        					.addGap(35)
        					.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 436, GroupLayout.PREFERRED_SIZE)
        					.addGap(40)
        					.addComponent(jLabel4, 0, 0, Short.MAX_VALUE))
        				.addGroup(panel1Layout.createSequentialGroup()
        					.addGap(109)
        					.addGroup(panel1Layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(lblNewLabel_1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addGroup(panel1Layout.createParallelGroup(Alignment.TRAILING, false)
        							.addComponent(btn04, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(btn03, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(btn02, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(btn01, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)))
        					.addGap(117)
        					.addGroup(panel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 530, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel8, 0, 0, Short.MAX_VALUE))))
        			.addContainerGap())
        );
        panel1Layout.setVerticalGroup(
        	panel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panel1Layout.createSequentialGroup()
        			.addComponent(panel2, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
        			.addGap(10)
        			.addGroup(panel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 271, Short.MAX_VALUE)
        				.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 271, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 256, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(panel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(panel1Layout.createSequentialGroup()
        					.addComponent(lblNewLabel_1, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(btn01, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        					.addGap(40)
        					.addComponent(btn02, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        					.addGap(33)
        					.addComponent(btn03, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        					.addGap(25)
        					.addComponent(btn04, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE))
        				.addGroup(panel1Layout.createSequentialGroup()
        					.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 241, GroupLayout.PREFERRED_SIZE)
        					.addGap(13)
        					.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 214, GroupLayout.PREFERRED_SIZE))
        				.addGroup(panel1Layout.createSequentialGroup()
        					.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 225, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 198, GroupLayout.PREFERRED_SIZE)))
        			.addGap(0))
        );
        panel1.setLayout(panel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(panel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        			.addComponent(panel1, GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed
            Admin_homepage ob=new Admin_homepage();
             ob.setVisible(true);
             ob.setLocationRelativeTo(null);
             this.dispose();
    }//GEN-LAST:event_btn01ActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
        // TODO add your handling code here:
        student_homepage ob=new student_homepage();
             ob.setVisible(true);
             ob.setLocationRelativeTo(null);
             this.dispose();
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn03ActionPerformed
        // TODO add your handling code here:
        Businessman_homepage ob=new Businessman_homepage();
             ob.setVisible(true);
             ob.setLocationRelativeTo(null);
             this.dispose();
    }//GEN-LAST:event_btn03ActionPerformed

    private void btn04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn04ActionPerformed
        // TODO add your handling code here:
        Tourist_homepage ob=new Tourist_homepage();
             ob.setVisible(true);
             ob.setLocationRelativeTo(null);
             this.dispose();
    }//GEN-LAST:event_btn04ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HomePage().setVisible(true);
        });
    }
    private java.awt.Button btn02;
    private java.awt.Button btn03;
    private java.awt.Button btn04;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private JLabel lblNewLabel_1;
    private Button btn01;
}
